version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: sigoe
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: /bin/bash -c 'rails s -b 0.0.0.0'
    depends_on:
      - postgres

volumes:
  postgres-data:
