version: '3.8'
services:
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sigoe_dev
      
  web:
    environment:
      RAILS_ENV: development